### ISSUE TITLE
Angular 6 Error TS2420 Property 'countReset' is missing in type 'Debugger'.

### ISSUE THREAD

**Issue by adammendoza** [DanielKucal/ts-debug#3]
I'm getting an error with Angular 6
```
ERROR in node_modules/ts-debug/debug.d.ts(1,22): error TS2420: Class 'Debugger' incorrectly implements interface 'Console'.
  Property 'countReset' is missing in type 'Debugger'.
```

**Comment by adammendoza** [comment]
I submitted a PR for it.

**Comment by DanielKucal** [comment]
Which TypeScript version does it actually affect?
Update: I see, it comes from `@types/node`.

**Comment by DanielKucal** [comment]
Implemented in v1.2.0

**Comment by adammendoza** [comment]
It affects typescript 2.7.2 which is the required version for Angular 6.


- Adam


________________________________

**Comment by adammendoza** [comment]
I'm still getting this error because it wants it as a property instead of a function. I'm using Angular 6 and it requires typescript@'>=2.7.0 <2.8.0' (I'm using 2.7.2). This package is required by ngx-store

```
@angular/compiler-cli@6.0.3 requires typescript@'>=2.7.0 <2.8.0' but 2.8.3 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.7.0 <2.8.0'

To disable this warning run "ng config cli.warnings.typescriptMismatch false".
```

**Comment by adammendoza** [comment]
btw: the suggested work-around does not work. 
```
To disable this warning run "ng config cli.warnings.typescriptMismatch false".
```

**Comment by DanielKucal** [comment]
> I'm still getting this error because it wants it as a property instead of a function.

@adammendoza, this can't be true, it's definitely a function as you can see in:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L53

I don't know exactly what is the reason, but I suggest you to try 2 things:
1. `npm i ts-debug@latest` in your project and then `npm i ngx-store`
2. Set `"skipLibCheck": true` in your tsconfig.json

**Comment by adammendoza** [comment]
Adding it to the app directly worked. Thanks!

Adam J. Mendoza
adammendoza@hotmail.com<mailto:adammendoza@hotmail.com>

On May 27, 2018, at 08:20, Daniel Kucal <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm still getting this error because it wants it as a property instead of a function.

@adammendoza<https://github.com/adammendoza>, this can't be true, it's definitely a function as you can see in:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/index.d.ts#L53

I don't know exactly what is the reason, but I suggest you to try 2 things:

  1.  npm i ts-debug@latest in your project and then npm i ngx-store
  2.  Set "skipLibCheck": true in your tsconfig.json
